language: php

php:
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - secure: "ZZfGf3xdnOlSHKp8vzw8JjoWebncAYa2GfHAAlBLmEHksx0KxmmtwkQ1wlUPS7aJK61IhnmJBcZ6mi18nQoYMpyF6BMpmh9ulWfYieuOMw9etJUM7IbUdKWYG+T2pUhOvMVLzVItwjBdV4mTdbIkOCNaD60vh/U+d2M2MnLVY0rH3Gzyj2EriGxV9n4QVJFqEUALV8Cg84ElZK4eKmap5QSDvDzMdkWJyLGus4US+gFTblsLzCwxwxXzFxa6uGF47QW4Se8HOV6oJRhuhV4aOSZvIhTdlsrckMjeWe/l9sfxWzHIwVqo+MALOL2qKCC79aqH3UNswK7Errv2Jdn9z7aU2ytcOZq3DpcOGPKfK89mSfL6J7m+BJSXPTqy6oooxD+puGMpsuYKIK+1auv5y8GLyt6gb6eEVLxiBcC5tZnOEyWuCTjJ0x2vP/L/Vzwu08eJVLEU24OWJ3dJsaO/w563O3a/l3BbGK/QwTLJGkpvu1/wfec1fyV6i1CqAvPD1VZLE6gtx1rXdtq595ims0D5Dnb3u4Ji1SrHWJeKmPbWyjsTOfq0iJjqvXH4Ld8H376Ssf97DUJLk9OCWJvz4C2C38NlbvmB5O3eSRX+bxIq5qTEdrWDYD0huZiiDb380/sumqpn2SwgSODnweYobO7dyCvwf6u0NtA7pDHwPnI="
    - secure: "YkuMxw3JXV5dhFEbcEYK8yD2+sNh6m3ap1h1ca1o7UAh4EefEoeC2SmLyGh1vaTf7rqcV841UDXvY6cKdgSQ/RZAokVsTocHpdA5FnOPcFDii+/GNyURiux46q+hVAv9Ff6ws52ofIO1Ip//d8dTFpq3NJ3sexObydOv9phuDpvH4bJuxjXm69BsQJnIBpOd5ky39kJSGz0Qr+SMv20jSaiyDEHGthMBRvubCWRRa6LVhprNB5whKb/GvNZR2H/2ObJ6/wbTx0GXD7IDOl+lUb4/5qNopJre6cL5TQzM6LZvxrpveYruDFe1lNrq3gnctlZuwKbPs9AEplx43VEdH5bUrWGJsAg4ervzza1/iCQG/EbLwGb6LpmpQFCYxZqc+DDWYusQX28A9Y6JTRKs0UAj93hHRtWYwEVZRO023m8Y1JQqdP1f8t+NWV1ywZGrlDVGHRNBQpVVyhj0tmv4RkXVTjLvFPK+tketlFVOI3uxPMGZ3eJklAuCr5FYDraAs/8Ye+zmyzm6gAaqyWR5ydibWg8CD4f3cnkR+1wHgGee2CuXcM1Ov0BzAa1OOVGIwDBVze2zMHZdHTPXvgtzTpZi1nQBWZzi+vGIOyhQ/yosyCU8jmQUguwKIlrtBEuRtUVWV3ARDDRaVtCYVvG3yZy/nclOQd1pVbeEwZcvEik="
    - secure: "SFr8U9ASR/96AYULF5smd0GaqjO2E1fVybH5BV7OgBH7zxhs8x4CXO6XUvMGq3pWKiWmjbwgkMD7w81BwNCg61i8bmm9JKxapVsfVqpOcu6HLhsKJPiOXgBKTxY9SayE/iSQI5DQGU8puCLdw4po+TETunX1aE7Ii8ahH9m66BvlCTtiUZF8aRZWLaiZgNgCajaQ/TCUJT2oRXnqqvRO1NixQC8/IRIa1S4lWThCzSko7IDmJ99X5aoOpxUXSi5WSNuigD5+OS668gfqnVJXFjN/ooRE3HptMlP11QlxpLBb6PFruXycEp0bIjoroKgEM0FeFOtzxjLlIdH3GvXfxsyy4qJOvGEIRiqCBXdByeyoAVQiChLmWwju8hR/Q7pNCZge6eNMqru7w2T1y8JS+O5PXrl9yMb8a1b8DiystfgHAZ5rQFlJ1BsGLB4HVyCMrRgpY2/kDPkfyypaRutSv8VklEoRdI/XyvoSZV04kt77ICYtemNoZEEb3CEqsWQzp0g/TdXMQfTthK+n6Y1QFphKfzZg3VD8tPWCI2zj2jQ2iGMZvKIpFnqx+i5YD7x4FDF/4jmAhgOfYIUZ0n55+r8WcPdfgZKKlKR9/722IOO+raP84R+3PooLTzpr/ew2hK17pHxFURq9BwW9M5XjiVPO91Eo9WRIhgPgYjQCVI4="

script:
  - composer install
  - vendor/bin/phpcs --standard=PSR2 *.php app tests
  - vendor/bin/phpunit

notifications:
  email: false

after_success:
  - find -type f -not -path "./vendor/*" -not -path "./.git/*" -exec curl -u $FTP_USER:$FTP_PASS --ftp-create-dirs -T {} $FTP_HOST/php-sorting-analysis/{} \;