language: php

php:
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - secure: "ZZfGf3xdnOlSHKp8vzw8JjoWebncAYa2GfHAAlBLmEHksx0KxmmtwkQ1wlUPS7aJK61IhnmJBcZ6mi18nQoYMpyF6BMpmh9ulWfYieuOMw9etJUM7IbUdKWYG+T2pUhOvMVLzVItwjBdV4mTdbIkOCNaD60vh/U+d2M2MnLVY0rH3Gzyj2EriGxV9n4QVJFqEUALV8Cg84ElZK4eKmap5QSDvDzMdkWJyLGus4US+gFTblsLzCwxwxXzFxa6uGF47QW4Se8HOV6oJRhuhV4aOSZvIhTdlsrckMjeWe/l9sfxWzHIwVqo+MALOL2qKCC79aqH3UNswK7Errv2Jdn9z7aU2ytcOZq3DpcOGPKfK89mSfL6J7m+BJSXPTqy6oooxD+puGMpsuYKIK+1auv5y8GLyt6gb6eEVLxiBcC5tZnOEyWuCTjJ0x2vP/L/Vzwu08eJVLEU24OWJ3dJsaO/w563O3a/l3BbGK/QwTLJGkpvu1/wfec1fyV6i1CqAvPD1VZLE6gtx1rXdtq595ims0D5Dnb3u4Ji1SrHWJeKmPbWyjsTOfq0iJjqvXH4Ld8H376Ssf97DUJLk9OCWJvz4C2C38NlbvmB5O3eSRX+bxIq5qTEdrWDYD0huZiiDb380/sumqpn2SwgSODnweYobO7dyCvwf6u0NtA7pDHwPnI="
    - secure: "huuHbJxaFB7fmIordHm+thCNv91AeJNPNnIxmYENW9RJhiz9tOfC2nwsY+U+U3feqZcFgYzarJKtx4untF+bXiRba2JVxVrhGV2H5fplDTsnigGObs+C1NmmoJ22+VVC7DimRb5+4LO68hGBU/7kxGN3rCMhYPNTRqVLVCKE5ewHpPC/PEpPlex4eoxIZ2J5dxi+3Bsr8034DUpLu5NgegvDVOHNZkZuyWdX/Lc35p5CHZSkJebW8ipfX7irK843nqPXjYDxpRK+4sI+6VEzW5tXfYTOn+gqEsfb9858ShghQ1OTRxPcgKJZdI1rFpa8kEjTM70x41V85QaLERiD5HA8sAjr6v4uje2+ULl2dO8s3d4tjE2q/mHDcLHXne3aTWQeXp/nMJP5W63m4xRq5BETQplaRGDc9EAR37gKaX2MyWnCHcw/S54KWJJPUVj/z0dD9z8vD9Am/TbNqUW89hDuUAlFOtKRWKo2zz28lGySBOkJ+JLnFKQ1XtV4QRZNR8XRK+F3Hr9l+qcOaF9kRCdA9D184OV2X6EBP7k3Pk7MZW3LR7hw9vHQjFPuMjWvxJ1HbuG0BURbqwROc9t6OoEf7Uqb0yscdnblJkiI5AMHUcbXGqyNuOtr24qLx6U6T9Tk7sCnm5mOzlE1eWDqpfdFEGSUn/g44Kg2PxKZX80="
    - secure: "SFr8U9ASR/96AYULF5smd0GaqjO2E1fVybH5BV7OgBH7zxhs8x4CXO6XUvMGq3pWKiWmjbwgkMD7w81BwNCg61i8bmm9JKxapVsfVqpOcu6HLhsKJPiOXgBKTxY9SayE/iSQI5DQGU8puCLdw4po+TETunX1aE7Ii8ahH9m66BvlCTtiUZF8aRZWLaiZgNgCajaQ/TCUJT2oRXnqqvRO1NixQC8/IRIa1S4lWThCzSko7IDmJ99X5aoOpxUXSi5WSNuigD5+OS668gfqnVJXFjN/ooRE3HptMlP11QlxpLBb6PFruXycEp0bIjoroKgEM0FeFOtzxjLlIdH3GvXfxsyy4qJOvGEIRiqCBXdByeyoAVQiChLmWwju8hR/Q7pNCZge6eNMqru7w2T1y8JS+O5PXrl9yMb8a1b8DiystfgHAZ5rQFlJ1BsGLB4HVyCMrRgpY2/kDPkfyypaRutSv8VklEoRdI/XyvoSZV04kt77ICYtemNoZEEb3CEqsWQzp0g/TdXMQfTthK+n6Y1QFphKfzZg3VD8tPWCI2zj2jQ2iGMZvKIpFnqx+i5YD7x4FDF/4jmAhgOfYIUZ0n55+r8WcPdfgZKKlKR9/722IOO+raP84R+3PooLTzpr/ew2hK17pHxFURq9BwW9M5XjiVPO91Eo9WRIhgPgYjQCVI4="

script:
  - composer install
  - vendor/bin/phpcs --standard=PSR2 *.php app tests
  - vendor/bin/phpunit

notifications:
  email: false

after_success:
  - find -type f -not -path "./vendor/*" -not -path "./.git/*" -exec curl -u $FTP_USER:$FTP_PASS --ftp-create-dirs -T {} $FTP_HOST/php-sorting-analysis/{} \;